---
services:
  # --- BBRsiAdxStrategy (1H BB+RSI+ADX) ---
  # FreqUI: http://localhost:8080 | VPS: https://freqtrade.kebodev.hu
  freqtrade_bb:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_bb
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ./user_data/strategies/bb_rsi_adx/.env
    command: >
      trade
      --logfile /freqtrade/user_data/strategies/bb_rsi_adx/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/strategies/bb_rsi_adx/tradesv3.sqlite
      --config /freqtrade/user_data/strategies/bb_rsi_adx/config.json
      --strategy-path /freqtrade/user_data/strategies/bb_rsi_adx
      --strategy BBRsiAdxStrategy

  # --- RangeBreakoutPullbackStrategy (5m Kitörés+Visszazárás) ---
  # FreqUI: http://localhost:8081 | VPS: https://freqtrade-rb.kebodev.hu
#  freqtrade_rb:
#    image: freqtradeorg/freqtrade:stable
#    restart: unless-stopped
#    container_name: freqtrade_rb
#    volumes:
#      - "./user_data:/freqtrade/user_data"
#    ports:
#      - "127.0.0.1:8081:8080"
#    env_file:
#      - ./user_data/strategies/range_breakout/.env
#    command: >
#      trade
#      --logfile /freqtrade/user_data/strategies/range_breakout/logs/freqtrade.log
#      --db-url sqlite:////freqtrade/user_data/strategies/range_breakout/tradesv3.sqlite
#      --config /freqtrade/user_data/strategies/range_breakout/config.json
#      --strategy-path /freqtrade/user_data/strategies/range_breakout
#      --strategy RangeBreakoutPullbackStrategy

  # --- SuperTrendMacdRsiStrategy (1H SuperTrend+MACD+RSI) ---
  # FreqUI: http://localhost:8082 | VPS: https://freqtrade-st.kebodev.hu
  freqtrade_st:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_st
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8080"
    env_file:
      - ./user_data/strategies/supertrend_macd_rsi/.env
    command: >
      trade
      --logfile /freqtrade/user_data/strategies/supertrend_macd_rsi/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/strategies/supertrend_macd_rsi/tradesv3.sqlite
      --config /freqtrade/user_data/strategies/supertrend_macd_rsi/config.json
      --strategy-path /freqtrade/user_data/strategies/supertrend_macd_rsi
      --strategy SuperTrendMacdRsiStrategy
